# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

Article.create(date: Date.today, title: "Oranges", author: "Adarsh Patel", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.")
Article.create(date: Date.today, title: "Apples", author: "Adarsh Patel", content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?")
Article.create(date: Date.today, title: "Kiwis", author: "Adarsh Patel", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Article.create(date: Date.today, title: "Grapes", author: "Adarsh Patel", content: "Auctor neque vitae tempus quam. Ut aliquam purus sit amet luctus venenatis lectus. Eget mi proin sed libero. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. A lacus vestibulum sed arcu non odio euismod lacinia. Et magnis dis parturient montes nascetur ridiculus mus mauris. Mauris a diam maecenas sed enim ut sem. Placerat duis ultricies lacus sed. Vitae sapien pellentesque habitant morbi tristique senectus et. Pulvinar neque laoreet suspendisse interdum consectetur libero id. Enim lobortis scelerisque fermentum dui faucibus in ornare. Nullam non nisi est sit amet facilisis magna etiam. Diam maecenas ultricies mi eget mauris. Urna neque viverra justo nec ultrices dui. Quam vulputate dignissim suspendisse in est ante in nibh.")
Article.create(date: Date.today, title: "Blueberries", author: "Adarsh Patel", content: "Risus viverra adipiscing at in tellus. Quis hendrerit dolor magna eget est. Ligula ullamcorper malesuada proin libero nunc. Auctor eu augue ut lectus arcu bibendum at varius vel. Adipiscing commodo elit at imperdiet dui accumsan sit. Ipsum dolor sit amet consectetur adipiscing elit. Sagittis vitae et leo duis ut. Leo vel orci porta non pulvinar. Enim facilisis gravida neque convallis a cras semper auctor. Amet nisl purus in mollis nunc sed. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ut venenatis tellus in metus vulputate eu. Amet dictum sit amet justo donec enim. Nec dui nunc mattis enim ut. In massa tempor nec feugiat nisl pretium fusce id. Id faucibus nisl tincidunt eget nullam non nisi. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Mauris cursus mattis molestie a iaculis at erat. Dictumst vestibulum rhoncus est pellentesque. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Morbi non arcu risus quis varius quam. Nibh nisl condimentum id venenatis a. Faucibus nisl tincidunt eget nullam non.")
Article.create(date: Date.today, title: "Strawberries", author: "Adarsh Patel", content: "Amet cursus sit amet dictum sit amet justo. Pulvinar elementum integer enim neque volutpat. Lobortis feugiat vivamus at augue. Consequat ac felis donec et odio pellentesque diam. Facilisis sed odio morbi quis. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Massa enim nec dui nunc mattis enim ut tellus. Nunc vel risus commodo viverra maecenas. Neque volutpat ac tincidunt vitae semper quis. Pretium vulputate sapien nec sagittis aliquam. Pretium fusce id velit ut tortor pretium viverra. Tincidunt tortor aliquam nulla facilisi cras fermentum. Sit amet cursus sit amet dictum. Maecenas ultricies mi eget mauris. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Neque laoreet suspendisse interdum consectetur libero id. Nulla pellentesque dignissim enim sit amet. Commodo viverra maecenas accumsan lacus.")
Article.create(date: Date.today, title: "Pineapples", author: "John Smith", content: "Lectus quam id leo in vitae turpis massa. Eget egestas purus viverra accumsan in nisl. Auctor neque vitae tempus quam pellentesque nec nam. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Tortor id aliquet lectus proin. Quam quisque id diam vel quam elementum pulvinar. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Semper feugiat nibh sed pulvinar proin. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Suspendisse potenti nullam ac tortor vitae purus. Magna sit amet purus gravida quis blandit turpis. Mattis vulputate enim nulla aliquet porttitor. Faucibus a pellentesque sit amet. Faucibus nisl tincidunt eget nullam. Ac auctor augue mauris augue neque gravida. Ut lectus arcu bibendum at varius vel pharetra vel turpis. Semper viverra nam libero justo laoreet sit. Odio tempor orci dapibus ultrices in.")
Article.create(date: Date.today, title: "Bananas", author: "John Smith", content: "Turpis in eu mi bibendum neque. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Ornare massa eget egestas purus viverra. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. In hendrerit gravida rutrum quisque non tellus. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Nunc sed blandit libero volutpat sed cras ornare arcu. Rutrum quisque non tellus orci ac auctor. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Risus quis varius quam quisque id diam vel quam elementum. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Sagittis orci a scelerisque purus semper eget duis at tellus.")