class ArticlesController < ApplicationController
  
  # GET /articles
  # Root action: renders all articles based on search bar
  # Will render specified articles based on text inside search bar
  # Will display all articles if there is no text inside search bar
  def index
    if params[:search].present?
      @articles = Article.search(params[:search])
    else
      @articles = Article.all
    end
  end

  # GET /articles/:id
  # Show action: renders article by id
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  # New action: generates a new article form
  def new
    @article = Article.new
  end

  # POST /articles
  # Create action: saves the data from the article form generated by new
  # Redirects user to the created article's page on success
  # Rerenders new form on failure
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /articles/:id/edit
  # Edit action: generates an edit article form
  def edit
    @article = Article.find(params[:id])
  end

  # PATCH /articles/:id
  # Update action: updates the data from the article form generated by edit
  # Redirects user to the updated article's page on success
  # Rerenders edit form on failure
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/:id
  # Destroy action: deletes article based on specified id
  # Redirects to root path (index) when completed
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private

    # Strong parameters, permits title, content, author and date
    # Used for create and update actions
    def article_params
      params.require(:article).permit(:title, :content, :author, :date, :search)
    end
end
