name: Run Tests
on:
  push:
    branches:
      - workflow-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rspec